- docassemble/assemblylinewizard/interview_generator.py
Does not include `plaintiff` and such. These are taken from an adjusted version of [this conventions documentation](https://github.com/SuffolkLITLab/doc-assembly-line/blob/master/variable_names.md) (which needs to be updated).
1. Fix `name_full` issues, though solution may be discussed.
1. Switch from `child` to `children`.
1. Add witness, court, and docket_number.
1. Add single-rule array for vars that only need a single rule to act on them.
1. Suggest some preliminary tests for the module
> Add conventions of most built-in PDF var names

- docassemble/assemblylinewizard/interview_generator.py
Otherwise words or sentences will be missing spaces.
> Replace new line with space (instead of empty string)

- docassemble/assemblylinewizard/interview_generator.py
- docassemble/assemblylinewizard/map_names_test.py
Fixes enhancement requested in #21
> Add attorney_of_record_address_on_one_line as whole reserved word

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
Fixes #81. This doesn't solve all the obstacles the docx var matching currently has, but it does solve this particular issue. See tests at https://repl.it/@plocket/docxvars#main.py and test with this Jinja:
```
Should NOT cause wizard prompts
{{users[0].email}}
{{users[0].address.address}}
{{users}}
{{users[0]}}
{{users[0].familiar_or()}}
{{users[0].birthdate.format("dd")}}
{{users[0].birthdate.format()}}
Causes wizard prompts because of unrelated functionality issues
{{users[0].address.block()}}
Should cause wizard prompts
{{users[0].mailing_address}}
{{user_has_name}}
{{users.number()}}
{{today()}}
```
> Allow docx arbitrary attributes. Fixes #81

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
Fixes:
* #114 
* #35 
If all questions are covered by basic questions, it spares the users from all of the specific details of setting types, and the screen looks like this instead:
Tested using this variant on the hello world docx: [hello_planet2.docx](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5858927/hello_planet2.docx)
> Interviews work with just basic questions

- docassemble/assemblylinewizard/generator_constants.py
Noted here: https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/pull/143/files/efb1b6a167aa827028aa5f6cd8aade3080572096#r56536262
> Adds missing leading `.`s to DOCX only suffixes

- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/test_map_names.py
- setup.py
Fix #157
Try this PDF in the weaver to see that `attorney_of_record_address_on_one_line` is not treated as a reserved word:
[atty_of_record_add.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5904668/atty_of_record_add.pdf)
> Fix #157, until implemented remove const `attorney_of_record_address...`

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
- docassemble/assemblylinewizard/test_map_names.py
- setup.py
Closes #67
Test 1:
1. Run generator-test.yml to confirm it appears there and passes.
Test 2:
1. Upload the below PDF
1. See that there are no unreserved vars created
1. (Should we allow people to create info screens even if they're only using reserved vars?)
1. See that yaml includes the right vars in the attachment block and the right vars in the interview order
[mail_address.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5912318/mail_address.pdf)
> Close #67, add `mail_address` to reserved suffixes

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
- docassemble/assemblylinewizard/test_fill_in_field_attributes.py
TL;DR: interviews before and after this PR should be the same, let me know if I should include more refactors in this PR. 
Starts work on #137, which even though it's a Future milestone, will make working on #127/#95 (yes no combination), #59, and #38 easier, as those all have to do with the review screen versions of fields. 
Before this PR, the `interview_generator` carried around a list of different fields, and when it needed to generate review block yaml, attachment block yaml, or field attribute yaml, it iterated through the fields and generated the yaml needed. This works, but is a bit confusing to navigate, results in a very large `DAQuestion.source` [method](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/blob/f457335d16ed33743f45468f9ee49966d5f02d3d/docassemble/asse …
> Phase 1 of Object Oriented Refactor: Fields

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
- docassemble/assemblylinewizard/test_fill_in_field_attributes.py
Fixes #38, #89
Requires #187 to be merged to master before this. 
Two sightly related fixes:
* #89 talks about merging the distinct uses of 'input type' and 'data type' when showing fields to the user. We can actually combine those two fields without losing information: all special data types don't make a ton of sense with the "area" or "yesno" field types. So we can combine everything into a single selection (which IMO makes more sense as a developer too. There is a difference between input type and the underlying data type, but the underlying data type should really determine the input type).
* #38: is a simply python formatted string. @nonprofittechy mentioned something about `thousands`, but I couldn't find anything about that in docassemble, and could only find …
> Only show user "field type", not input and data types + Format numbers

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
This fixes #165 and #88 
It lays some groundwork for #163.
Putting in the PR now just so we can test this discrete code for now, but I'll keep on the same branch or a PR to this branch.
> Add objects block for all people in generated interview, allow limiting number of people to exactly 1

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
Fixes #132.
Some of the choices I made feel a little hacky; I couldn't find a better place to get docassemble to run the `interview.allowed_courts_text` conversion than in the one block that it's used. Let me know if there's an better solution there that I missed.
Example of the UI is show below:
> Allow modifying court choices as constants, or during weaving

- docassemble/assemblylinewizard/interview_generator.py
> Close #193, replace underscores with dashes in user-facing file names. One line.

- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
- docassemble/assemblylinewizard/test_map_names.py
Closes #207. [Also uses and thus closes #205. For the regex used, see the last link in that issue. Does it also close #179?] Took care of it in 4 places:
1. PDF var name mapping
2. DOCX var name mapping
3. With trigger gather var names
4. When collecting people
I treated it like a person who is singular as it seemed to match those criteria in behavior.
Test 1:
Test 2:
Use ([trial_court.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5951154/trial_court.pdf)) and see that `trial_court`:
Test 3:
Use ([trial_court.docx](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5951187/trial_court.docx)) and see that `trial_court`:
Test 4:
Did I miss anything?
Notes:
1. There is a console log coming out of interview_generator and I'm wondering if that …
> Close #207, add singular Person prefix to global_constants (trial_court)

- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
Tested a little, but still might have some (related or unrelated bugs). 
Main parts:
* replaces `unmap` with a more general `substitute_suffix`, from any dictionary
* adds a `_get_base_variable` to `DAField`, which gets the base list, object, or variable that holds the data for the field itself. This is used to make sure there aren't duplicates on the review screen. 
Should fix #59 and also fix #178, and a small portion of #64 (still need to handle the name I think).
> Review screen full display

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
* Add back None of the Above for Courts. I removed it at one point, I thought it was breaking things, but it's fine now. 
* If Other is selected for court names, make the user specified "Other" courts required. Without this change, the code that removes "Other" and replaces it with the alternate courts (https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/blob/1fa5d4fdd191369d679c8adccb3ef6a26dcbdf48/docassemble/assemblylinewizard/data/questions/assembly_line.yml#L415)  is never run. Since None of the Above is back too, I'm fine making this required.
> Fix Lingering "Other" in allowed_courts causing errors in resulting interview

- docassemble/assemblylinewizard/data/questions/pdf_field_tester.yml
Closes #259 with a super simple metadata block for the pre-flight interview.  
Also restricted upload types to PDFs only, as anything else will error right now.
> Added metadata to PDF pre-flight interview

- docassemble/assemblylinewizard/data/questions/pdf_field_tester.yml
Am in the process of trying to patch this upstream, but patching here is quicker. Can confirm it works.
> Also patch PDF Preflight checker when it has no fields

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
Solves #101 .
The major thing happening in this PR is that `DAField.raw_field_name`, a single string, is turned into `DAField.raw_field_names`, a list of names of all of the PDF field names that are directly tied to this variable. Most changes are fixing all uses to use a list instead of a single string.
The other major thing is actually using these multiple field names:
* `raw_field_names()` is populated by calling `consolidate_duplicate_fields()` and `consolidate_yesnos()` on DAFieldList
* it's used in 'attachment_yaml()', where we map the backing variable back to all of it's uses in the PDF, all of the different names.
Added some extra types to strings as well
> Deduplication of pdf

- docassemble/assemblylinewizard/custom_values.py
- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
Fix #287. Tested with [review_screen_people.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6086692/review_screen_people.pdf) and [review_screen_people.docx](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6086695/review_screen_people.docx).
`foo` is the custom people list variable. It should have:
> Fix #287, custom people are missing appropriate endings

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
Refactoring the review screens by adding revisit screens, which fixes quite a few issues:
Fixes #270 
Fixes #64 
Fixes #120 
Kinda address #115, not directly, but in spirit. Not sure we need to address things by screens.
Revisit screens show all of the attributes used for a specific set of objects and let you edit them (entries are blank if they aren't filled in yet).
It does that with the new class, `ParentCollection` that collects variables that all share the same "Parent variable", i.e. the same list or object variable. The ParentCollection in general outputs a much better review screen, and can spit out its own table and revisit screens if necessary.
More testing is always welcome, but it should be okay? I'll remove this line when I'm certain it's bug free.
> Review refactor

- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
There might be a ticket somewhere about this, but I can't find it. We have definitely discussed this in Monday meetings before though.
`PEOPLE_VARS` and `RESERVED_VARS_PLURALS` are explicitly redundant to the `RESERVED_PERSON_PLURALIZERS_MAP` and `RESERVED_PLURALIZERS_MAP` values, containing the same entries, but with less information (the latter also containing the singular versions of the words).
This PR just removes them. I tested on a docx and a PDF, which still output correctly. Things should stay exactly the same (unless some function was modifying a global... :eyes:)
> Removed redundant generator constants

- docassemble/assemblylinewizard/interview_generator.py
Just a small change to where we're checking `people` from. Fixes #286.
> Try reserved_pluralizers_map

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/data/sources/output_patterns.yml
fix #296
Add date of generation and version number of weaver, if available, to the form-specific metadata. If the weaver is run from the playground (which you may do in your review) it will display "playground" as the version number as it has no accurate way to access anything more specific.
> 296 add version number

- docassemble/assemblylinewizard/interview_generator.py
When fixing #286 by removing non-people object from custom people, I introduced an issue where custom people (now not including non-people like docket numbers, etc.) were removed from non-custom people (which did still include non-people objects), leaving the non-people objects still!
Now, non-people objects are removed from both.
> Fixes #346, stop including numbers and courts as people.

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
Closes https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/issues/322, although more work is needed to incorporate more jurisdictions (#149).
Adds a separate screen to select the packages to include. It could be shoved into another screen, but would be much less understandable. Made the screen have good defaults, so we should be able to just continue 99% of the time.
> Dependencies in generated interviews

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/data/questions/pdf_field_tester.yml
- docassemble/assemblylinewizard/interview_generator.py
Fixes #261 by immediately stopping the weaver on PDFs that have variables that we can't turn into valid python identifiers. Started trying to check if we could check for invalid python in DOCX, but that would take a bit more refactoring, so I left that as a TODO.
Also added the check to the preflight tool, and cleaned that up a bit.
> Stop on invalid names

- docassemble/assemblylinewizard/interview_generator.py
- setup.py
Fix #228. Trigger is 100 characters.
Tested with 
[Fax_cover_sheet.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6461673/Fax_cover_sheet.pdf)
> Guess dataype "area" if the input is > 100 characters for a PDF

- docassemble/assemblylinewizard/interview_generator.py
Fixes #275. We now only try to use PDF heuristics on PDF files, and DOCX heuristics on DOCX files.
Some test files:
[Test_custom_names.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6466775/Test_custom_names.pdf)
[Test_custom_names.docx](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6466776/Test_custom_names.docx)
> foo_name is no longer treated as a custom person in DOCX files

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/interview_generator.py
Just stops people from 0 indexing lists of people in PDFs. Should be consistent and stick with 1 indexing.
Due to some refactoring of `map_raw_to_final_display` (i.e. `map_names`), this depends on https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/issues/603 (branch in progress) and should be merged after so it doesn't break any MAVC interviews.
> No more 0 indexing 300

- docassemble/assemblylinewizard/interview_generator.py
Stopped using custom_trigger_gather, it just works :tm:. Fixes #366. Tested with 
[dta_employment_info.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6503439/dta_employment_info.pdf).
When this was first [implemented](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/commit/f3a410be0169ae3c75c065349bbb811b26d25a13#), we weren't passing custom people to `trigger_gather()`.  After https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/commit/45b0735ff3861e2c86f2c7e6bdcaedc108db7b9d we are, so the original implementation isn't needed.
Potential downside: only the specific PDF label referenced is triggered. I.e. `employee1_address_address` only asks for `employee[0].address.address`, and not `employee[1].address.address`. Works for the form, …
> Allow custom attributes on custom people objects

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/data/sources/output_patterns.yml
Fixes #354. Tested on a PDF and DOCX, though I had to modify them for alternate reasons (seems I only have bug-trigger testing docs on hand and nothing that really works).
> Don't display "send editable" on pdfs

- docassemble/assemblylinewizard/generator_constants.py
- docassemble/assemblylinewizard/interview_generator.py
Adds a special dictionary with variables that are primitive lists, notes that they don't have attributes to show in tables, and makes a new table for them.
> FIxes #375, special cased docket numbers into a table

- docassemble/assemblylinewizard/custom_values.py
- docassemble/assemblylinewizard/data/questions/assembly_line.yml
Does three things:
* splits the dependency question into "jurisdiction" and "organization"
* puts the selected dependencies into the `include` block
* Sets up the ability to read dependency information from an installation specific yaml file in the `sources` dir. Future work there will be a write an interview that writes that file with github organization info, extra dependencies to possible add, defaults, and eventually, things from `generator_constants.py` like Court types.
The yaml stuff seems a bit hacky, but only because of docassemble's persistent files in packages and playground vs installation differences.
> Actually include selected packages

- docassemble/assemblylinewizard/data/questions/assembly_line.yml
- docassemble/assemblylinewizard/data/questions/pdf_field_tester.yml
- docassemble/assemblylinewizard/interview_generator.py
Fix #401 and add a few other safety checks:
* Invalid Xref table
* PDF cannot be concatenated
* PDFs with unusual field tuples
* Warn about XFA forms (all_fields is an empty list instead of None)
Some of these may be obsoleted by upstream fixes, but this will offer a little safety for people on older docassemble versions.
Some files that will give helpful error messages:
* [Fax_cover_sheet_corrupt.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6581278/Fax_cover_sheet_corrupt.pdf)
* [not_a_pdf.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6581281/not_a_pdf.pdf)
* [ma_seal_criminal_records(1).pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6581279/ma_seal_criminal_records.1.pdf)
* …
> Add pdf safety

- docassemble/ALWeaver/data/questions/assembly_line.yml
Resolves #461 by making the statements that build the objects and attachment blocks idempotent.
After this fix, you should see only one attachment for the main document and one for the instructions, and just one objects block for the main document and one for the instructions.
[single_field.docx](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/6886902/single_field.docx)
In testing this bug I also noticed #464 which I will look at in a separate branch.
> Fix #461 - make .append() statements idempotent

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/sources/output_patterns.yml
This groups some minor additions to the output YAML that slightly reduce developer friction and fix two bugs. Hopefully grouping this way is convenient; in queue I have more that I could do as 4 PRs or one that has a few related small changes.
Fix #472 
Fix #467 
Fix #451, fix #452
Fix #453 
Fix #363 
Fix #306
> Enhancements to output YAML - enhance generated "getting started" page and bug fixes

- docassemble/ALWeaver/interview_generator.py
Fix #450  - fields ending in _amount or _value default to "Currency" datatype
Fix #468  - Capitalize field names in review screen and revisit table
Sample document with both _amount and _value fields as well as some revisit tables
[FeeWaiver_Civil_Application.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/7011207/FeeWaiver_Civil_Application.pdf)
> Improve appearance of review screens and default handling of field names associated with currency

- docassemble/ALWeaver/interview_generator.py
Fix  #464
It turns out the issue in #464 was mostly user error (alien_ambassador was not given a list index), however, there still was an issue with DOCX files that have an index of `0` wrongly triggering an exception. This PR fixes that issue.
[Test_custom_names.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/7069970/Test_custom_names.pdf)
[hello_planet2 - Copy.docx](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/7069971/hello_planet2.-.Copy.docx)
> Fix use of custom people in DOCX files

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/sources/output_patterns.yml
1. Uses the author name for "About" page and for package setup.py
2. Add a way for authors to set the initial value of AL_DEFAULT_COUNTRY and AL_DEFAULT_STATE. Defaults to US and MA, respectively, for now.
Fix #267 
Fix #382 
Fix #383 
Fix #384 
To test:
1. Add a few author names when prompted.
2. Verify that the first author is listed in setup.py
3. Verify that other authors appear in the `metadata` and in the `about` page
4. Add a default state and country
5. Verify that the interview can run and that the values of `AL_DEFAULT_COUNTRY` and `AL_DEFAULT_STATE` get set to ISO 2 or 3 letter codes.
> Allow a little more personalization of interviews + add default state/country

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/pdf_field_tester.yml
I made these changes a while ago and wanted to give a demo, but our schedule has been too full lately so I am going to push them to this branch before I lose sight of it.
The main changes were converting the radio buttons to checkboxes, which also triggered some text rearrangements. In addition, one thing strange about the checkboxes is that it seems only the "Continue" button can execute the validation code, any other buttons would have no connection with what's on the current screen, so I added an "exit" screen to the tester, not only to get around this problem, but also to end the testing process properly, i.e. to give the user (especially those who only does the labeling) a sense of closure, and also to record a "complete line of actions" in google analysis via the screen IDs.
> Streamline PDF checker

- docassemble/ALWeaver/interview_generator.py
Fix #500 
You can test with the file uploaded to #500 , and directly test the regex on regex101.com
Regex:
```
{%[^ \t]* +if ([^\} ]+) ==|is|>|<|!=|<=|>= .* +[^ \t]*%}
```
Sample text:
```jinja2
{%p if will_type == “testate” %}
Testate (Decedent Died with a Will) 
•	Petition for Formal Probate of Will/Adjudication of Intestacy/Appointment of PR (MPC 160)
•	Surviving Spouse, Children, Heirs at Law (MPC 162)
•	Devisees (MPC 163) 
•	Original Will, if available, if not, a copy or statement of Will contents
•	Certified Copy of Death Certificate, if available or affidavit
•	Citation- Return of Service (MPC 560)
•	Decree and Order on Petition for Formal Adjudication (MPC 755)
{%p if wants_personal_representative %}
•	Bond (MPC 801)
{%p endif %}
•	Military Affidavit (MPC 470)
•	Authenticated Copy …
```
> Fix #500 - identify variables in `if` tests

- docassemble/ALWeaver/data/sources/output_patterns.yml
Add `skip undefined` as a default for DOCX files now that it is available, to mirror behavior of PDF files.
This feature will help us add a custom error handling page that lets someone recover a document that is in progress when Docassemble runs into a bug.
> Turn on `skip undefined` by default for DOCX templates

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/pdf_field_tester.yml
Closes #521. I wasn't able to find a (free) way for humans to fix this without losing the functionality of interactive elements of the form. Feel free to edit the error page if you know more. Also fixes an outdated variable name.
> Adds an exit screen for another PDF parsing error

- docassemble/ALWeaver/custom_values.py
- docassemble/ALWeaver/data/questions/assembly_line.yml
> Fix #539, `objects_from_file()` is now in docassemble.base.util

- docassemble/ALWeaver/data/questions/assembly_line.yml
Addresses #538. [Can't be tested until #540 is merged to fix the error.]
> Address #538, add var for ALKiln tests to compare YAML output as text

- .github/workflows/tests.yml
- docassemble/ALWeaver/advertise_capabilities.py
- docassemble/ALWeaver/custom_values.py
- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/config.yml
- docassemble/ALWeaver/data/sources/configuration_capabilities.yml
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/requirements.txt
This lays the groundwork to allow all kinds of Weaver customizations. The current version offers just one:
* list of state and organization dependencies.
Customizations are contained in a YAML file, `configuration_capabilities.yml`. If a package has a `configuration_capabilities.yml` that
it wants to advertise, it uses the `advertise_capabilities()` function to add an entry into a `DAStore`. The Weaver then scans the DAStore to look for available customizations.
Customizations are versioned to allow for future breaking changes.
This first set of customizations is purely additive--adding the configuration_capabilities expands the list of dependencies the interview author can choose from. Future vision is to allow the interview author to make some selection between customizations at the …
> Use a DAStore to hold configuration settings

- docassemble/ALWeaver/data/questions/assembly_line.yml
This changes the way that the interview_label is created so that it matches not just the rules for variable names but also the filename sanitization methods that are used by werkzeug.utils.secure_filename(). Docassemble upstream limits the filenames in the playground to those that pass the werkzeug.utils.secure_filename() sanitization rules, so this helps ensure that packages we create in can be edited in the Playground.
This patch also makes the interview_label lowercase by default and renames the template and YAML to match the interview_label.
Fix #561
~Edit: give me a sec to make sure the filenames of a generated interview still all match up, sorry!~ Ready to be reviewed.
If you want you can try running the Weaver with the filename that started this all: `01 - Intake NOTES w all …
> Sanitize filenames

- docassemble/ALWeaver/data/questions/assembly_line.yml
While the "I'm feeling lucky button" was taking 19 seconds to run, I decided to see why it was taking that long. It seem that the largest timesink was that DA was taking 10 seconds to generate all of the DOCX forms for the next steps (~2 seconds per form to get the libreoffice lock), even though only one was being used.  I did a simple I'm feeling lucky test with this code (installed it on the Dev server for ~5 minutes and triggered a run from the form-explorer during that time) and things worked. It's not extremely snappy, but we did take off 8 or so seconds from clicking the button to seeing the "done" screen.
> Separate out the next_steps generation to speed it up

- docassemble/ALWeaver/data/questions/pdf_field_tester.yml
- docassemble/ALWeaver/interview_generator.py
- setup.cfg
There's a small warning when install the Weaver:
`Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead`
No explicit removal version is given anywhere, but might as well change it.
https://setuptools.pypa.io/en/latest/history.html#id239
`labels above fields` is only an initial/feature block feature, or per field, not per question.
> description-file -> description_file and bad attribute in block

- docassemble/ALWeaver/data/questions/docx_field_tester.yml
- docassemble/ALWeaver/validate_docx_files.py
Docx2python recently released version 2, which adds a DocxReader insteance to
the docx_data object returned by docx2python. I'm pretty sure that it's
considered a "_io.BufferedReader" object, which can't be pickled and causes
an error in docassemble when it remains in the global variable space.
https://github.com/ShayHill/docx2python/blob/master/changelog.md
> Moves the use of docx2python into a module

- docassemble/ALWeaver/generator_constants.py
- docassemble/ALWeaver/interview_generator.py
- setup.cfg
- setup.py
fix #574
Before, the "send overflow text to addendum" checkbox was displayed for every input when weaving a PDF form. This could easily lead to user error, as in #574, where a user sent a "float" value to the addendum, causing a type error. This PR changes it so that the "send to addendum" checkbox is only displayed if the user selects "datatype: area".
Test by weaving a PDF and changing the datatype of an input to `area`. You should not see the addendum checkbox for any other input type, nor when weaving a DOCX file.
> Display the "send overflow to addendum" checkbox only on `datatype: area` inputs

- docassemble/ALWeaver/interview_generator.py
- setup.cfg
- setup.py
Fix #560 (problem when people use an apostrophe inside a field label)
It turns out there are very weird rules about how to escape strings in YAML. We could use one of the many line continuation markers in combination with the `label` key for a Docassemble field, but that makes all of our `fields` statements harder to read and less idiomatic. We could remove quotes, which would mostly work, but it could cause problems when people use special symbols like `:` or the literal words `yes` and `no`. This fix just stops escaping quotes that can't be escaped in that position in a YAML file and leaves the rest alone.
> Properly escape quotes in field labels

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/sources/output_patterns.yml
- setup.cfg
- setup.py
Fix #441
This adds a code block that sets the value of `addresses_to_search` to the user's address in court-related forms. Currently, this block is used in the ALMassachusetts forms. In the future, more jurisdictions will be able to help litigants figure out venue based on addresses though.
Expected behavior:
If someone selects that the form is court related, a block that defines `addresses_to_search` will be added. If they select that the form is NOT court related, no such block is added. The contents of the block, if it is added, do not depend on any input from the user.
> Create a placeholder "addresses_to_search" definition in court-related forms

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/interview_generator.py
Add some more ways to set datatypes in the Weaver. Specifically, add support for:
* noyes
* noyesradio
* yesnoradio
* file
* combobox
* multiselect
* dropdown
And add support for simple Python expressions. E.g., `some_var = 123`. And for "skipping" a field, which will set the value of the field to DAEmpty() as a decent placeholder.
Fix #513
Fix #512 
Fix #135
> Add more datatypes

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/validate_docx_files.py
Two different fixes in the same document (only because my example had both of those errors):
* If you have a possible person variable, the Weaver tries to map the string to a python variable. However, it isn't passing around the document type where it should, so it considers some DOCX variables as PDF variables, and will error if you include a valid 0-indexed DOCX person variable. This adds the correct document type to the proper functions.
* Fixes https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/605 by creating a DA environment closer to what DA actually does when running DOCXs through Jinja.
Tested with this document:
[test_manual_line.docx](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/8702889/test_manual_line.docx)
> Fix 0th docx & Allow `manual_line_break`

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/interview_generator.py
- setup.py
This was a weird series of hard to debug problems. Really makes we wish we made this logic a bit more declarative, which is something we've had in progress before (using a single declarative mako block to structure the output instead of loading each one separately with unique parameters.)
I left in some very small refactors that were part of my trying to track the cause of this down.
1. The PDF / DOCX checkers weren't being loaded at the right time because a block used to set some defaults was being given the wrong priority. Added a `scan for variables: False` kludge to that for now. We can reexamine the need for this block later. Might be better to set some conditions in the places those variables are being set.
2. Although we were getting an error about interviews.blocks[6].data, it was …
> Hotfix survey interview

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/docx_field_tester.yml
- docassemble/ALWeaver/data/questions/generator-test.yml
- docassemble/ALWeaver/data/questions/pdf_field_tester.yml
- docassemble/ALWeaver/field_grouping.py
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/validate_docx_files.py
- mypy.ini
- setup.py
I think this is ready for review a little earlier than expected (replaces #631). This PR allows you to automate multiple (related) forms in one Weaver session. Each template is added to the output's bundle and a separate attachment block is added for each file, but the user experience is a single interview. There is no special feature that lets you separate out the documents once the interview is generated.
A lot of code was touched to reach this result.
- Some field handling code that had to deal with both PDF-style tuples and DOCX-style string fields was removed. Instead, the fields are put into a single list of DAFields. The source document type is marked for use when necessary.
- Much code in the YAML was abstracted and placed into the interview_generator.py file
- Some functions in …
> Automate multiple forms in one Weaver run

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/interview_generator.py
We had a nice feature to catch the use of PDF variable name syntax in DOCX template, but we weren't properly passing the document type in some cases, leading to exceptions that should only apply to PDFs being raised.
This just adds the DOCX filetype in some places that was required but missing.
Example DOCX that should work but didn't before: 
[93A demand letter - partially labeled.docx](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/9758217/93A.demand.letter.-.partially.labeled.docx)
> Let a DOCX template contain a zero-based index

- docassemble/ALWeaver/data/templates/output.mako
Otherwise, in interviews where the role is already known (via form semantics or e-filing info), we end up asking the user what side they're on, and immediately ignoring their answer. Wider issue in
SuffolkLITLab/docassemble-AssemblyLine#596.
> Change user_ask_role to user_role

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/data/templates/output_defs.mako
- docassemble/ALWeaver/interview_generator.py
Improve Weaver's safety - use skip undefined and separate attachment blocks for instructions.
Fixed an undiscovered bug with Addendum code
Misc. cleanups to output YAML
Fix #721 
Fix #720 
Fix #719 
Fix #728
> Output pattern roundup

- .github/workflows/unit_tests.yml
- setup.py
* use action logic from ALActions/pythontests
* use `scikit-learn` instead of `sklearn`: https://github.com/scikit-learn/sklearn-pypi-package
Might do a quick install test (that Kiln wouldn't cover) since I am changing setup.py.
> Update python test action

- docassemble/ALWeaver/data/questions/template_validation.yml
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/test_fill_in_field_attributes.py
* fills in the first radio button in each group of buttons
when asking the user to make sure we filled in value correctly
* recognizes radio buttons by their export value not being "yes" or "on"
* consolidates the duplicate entries that we get from the PDF reader
into a single DAField
* default their input type to multiple choice radios,
and gives their default values for choices
Fix https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/75.
Tested with [ExampleAdobePDF.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/10829211/ExampleAdobePDF.pdf)
can also make sure to test with:
* [radios.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/10829216/radios.pdf)
* [pdf-radio-buttons.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/10829217/ …
> Radio buttons in weaver

- docassemble/ALWeaver/custom_values.py
- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/test_fill_in_field_attributes.py
- docassemble/ALWeaver/test_pdf_files.py
Remove `custom_values`, and replace it with DAFieldList.custom_people_plurals,
passing it through to all of the functions necessary.
Fixes #559.
Tested with multiple simultaneous sessions, and manually going through and making sure the final interview handles the custom plural person variables right.
> Idempotency & multiple session module issue fixed

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/template_validation.yml
This particular `pdf_concatenate` is now redundant, and can be removed.
> One fewer pdf_concatenate to sit through

- docassemble/ALWeaver/data/questions/template_validation.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/generator_constants.py
- docassemble/ALWeaver/interview_generator.py
This is a little hacky but there's not a clean way to add support for these two variables types in generator_constants yet:
- objects that are predefined at the class level but have an undefined attribute, like name.first
- nested lists
Makes me wonder if we can really use a declarative DSL to handle all of the various kinds of objects we want to handle in various ways--maybe it will never be flexible enough?
Alternatively -- we need a special table of "trigger variables" rather than the very complex way we guess them based on the current classification of variables in generator_constants.py
I think hack is the right choice until we can come up with a broader refactor. Either way, these two new variables have a general use so we should figure out how to permanently support them.
> Add namechange questions

- docassemble/ALWeaver/interview_generator.py
Fixes #781. Defaults to having simple description text separate from the key for radio buttons, moves the hint text to the help, and adds a simpler hint text (which isn't really great UX anyway since it disappears, but eh).
> Better radio defaults

- docassemble/ALWeaver/data/questions/assembly_line.yml
Labels are computed before the screen is shown, and this one part was missed in https://github.com/SuffolkLITLab/docassemble-ALWeaver/commit/87581a85d561bce8cd9acd640f960847a86be56e.
> Make custom button work again

- docassemble/ALWeaver/data/questions/review_screen.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/interview_generator.py
Fixes #763, and has slightly better display of signatures on the final screen.
Missing from this PR: the review screen shows all signatures as "built-in" screens, which isn't true after this change. Couldn't find a good way to edit that that didn't seem hacky, so I'll make a new issue.
> Define new signatures for output interviews

- .gitignore
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/test_pdf_files.py
Was the reason that we turned off custom people for LITCon. Before we turn it
back on, we should stop the cause of false positives.
Decided to hardcode the ending to avoid "_name" in the method for now; I don't
think we need to make it general now, as it's kinda hacky, and still needs a
better long term syntax to handle when people want things to be objects or
people, like #96.
Also did some small cleanups; to avoid looking at those, just look at https://github.com/SuffolkLITLab/docassemble-ALWeaver/commit/2453f40624efa9c35eaa26be63989de23f62636f.
> Avoid  name

- docassemble/ALWeaver/interview_generator.py
Should show the original PDF field name, not our transformed version if and when possible.
First in a series of small changes here, more to come.
With this PR, information shown on the bad names screen:
```
The fields that have issues are:
Some text fields have no name. In the PDF, they are called `25, `26, `27, `28, `29, `30, 
`31, `32, `33, `34, `35, `36, `37, `38, `39, `40, `41, and `42. All field names should be in snake case.
```
Information shown on main:
```
The fields that have issues are:
A text field has no name. All field names should be in snake case.
```
Test PDF: [Coding Form.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/11234312/Coding.Form.pdf)
> Show more info about bad names

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/template_validation.yml
- docassemble/ALWeaver/interview_generator.py
Can across some PDFs that had fields had bad Adobe names (like \`25, etc.), but
Gavel wouldn't show those fields, so authors with those PDFs aren't able to
progress.
We have the ability to just not fill in certain fields in the docassemble, and
this patch allows authors to continue with the Weaving process if they don't
care about the shown fields.
Example PDF to test with: 
[test-custom-name.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/11236597/test-custom-name.pdf)
Should be able to progress by selecting "I know what I'm doing, ignore these fields and continue", and you can make a full interview without the badly named "`25" field.
Realizing I could make a Kiln test for this. Willing to do that, but it'd take some more time.
> Ignore bad field names

- docassemble/ALWeaver/data/questions/template_validation.yml
- docassemble/ALWeaver/interview_generator.py
We used to warn folks when they didn't have any fields, but an older change (https://github.com/SuffolkLITLab/docassemble-ALWeaver/commit/c51b30646d3bc80d4b8b1c84b85778e5db58011e) broke that functionality by assuming that all PDF objects had an AcroForm attribute. This patch does not assume that, and can correctly show the user the better error screen.
Tested with PDF:  [AL.PDF.pdf](https://github.com/SuffolkLITLab/docassemble-ALWeaver/files/11236728/AL.PDF.pdf)
Fixes #802.
> Work on forms without AcroForm

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/templates/output.mako
Going to merge after tests pass.
Fix #830 - just add the `tagged pdf: True` modifier to attachments, including next_steps
Fix #397 add in a field with more information about the topic in the PDF
Fix #832 - use the metadata dictionary, don't rely on the interview_metadata dictionary for anything anymore
These are preparation for adding a new page to let someone customize the next steps document
> Continue work on courtformsonline.org prep, next steps enhancements

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/review_screen.yml
Closes #842
It turns out these were mostly caused by an `only sets` modifier. I assume that was added to resolve an issue with Docassemble's variable scanning function sometimes triggering the block at the wrong time. I added each of the undefined variables mentioned in the relevant block to the `only sets` which should be safe as they each are only mentioned in that block and the specific error screen triggered only from that block.
Some other undefined variables were caused by issues with how variable scanning works in the `review` page and by unnecessary and unused `revisit` blocks created by the review screen generator.
#847 fixed the one true error reference in #842
> Clear "undefined names" in Playground

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/review_screen.yml
- docassemble/ALWeaver/data/sources/test_1.feature
Bryce I'll merge w/o your review, just a courtesy notice
> Lucky remove extra screens

- docassemble/ALWeaver/data/questions/review_screen.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/interview_generator.py
Fix #872
For what it's worth: the test failure appears to be a red herring. I ran all of the (unchanged) test PDFs through the Weaver without any issue. And the mypy test failure is due to a disk space issue on the runner.
Error screen from Kiln (which looks like a false positive):
> Don't add next steps documents to the YAML or package if the author requests not to add them

- docassemble/ALWeaver/data/questions/template_validation.yml
- docassemble/ALWeaver/validate_template_files.py
Fix #878: use the API key when it's in the config
Fix #877: use a more reliable method to detect whether a PDF has any form fields (e.g., directly check the Acroform rather than looking for annotations)
> Field recognition bugs

- docassemble/ALWeaver/data/questions/assembly_line.yml
Fix #875
1. Defaults to the interview title instead of the original filename, as someone is more likely to cleanup the title.
3. Provides an option to customize the interview label
> Allow customization of interview_label

- docassemble/ALWeaver/data/questions/assembly_line.yml
1. Fix #896  - set `multi_user = True` so the "share" link does what it says it will do
2. Fix #691 - Add the filename, and then the title, of the interview in progress to the session list so it is simpler to locate the interview you were in the middle of working on.
3. Filter the list of sessions in the "Load a previous project" list so it only shows interviews past page 1.
> Improvements for working with longer sessions in the Weaver

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/interview_generator.py
Fix #905 
Create an API for #907 (not used yet)
This is intended as an intermediate "bridge" step that will let us take the output of GPT3/4 and use it to author the skeleton of an interview in JSON format. The Weaver uses the skeleton + the original file (DOCX or PDF) to make a full-fledged Weaver interview.
This is a new, experimental feature that I might demo at Jurix next week, and it doesn't interfere with existing features. I've tested it. Going to merge for now but I welcome more refinements.
> Allow uploading a "script" for interview auto drafting mode

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/sources/test_1.feature
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/generator_constants.py
- docassemble/ALWeaver/interview_generator.py
See: https://github.com/SuffolkLITLab/courtformsonline.org/issues/8
fix #924
> Add metadata fields to the output of the Weaver to help with publishing to courtformsonline.org

- docassemble/ALWeaver/data/questions/assembly_line.yml
- docassemble/ALWeaver/data/questions/template_validation.yml
- docassemble/ALWeaver/data/templates/output.mako
- docassemble/ALWeaver/interview_generator.py
- docassemble/ALWeaver/requirements.txt
Fix #933 
1. Checks the uploaded document for fields before attempting auto drafting mode
2. Skips some metadata that we added in #925 when autodrafting is used (rather than awkwardly prompting the user)
3. Map the jurisdiction code to LMSS jurisdiction code, if the jurisdiction provided looks like the abbreviation for a US state.
> Don't try "auto drafting" with an empty PDF or DOCX file
