SuffolkLITLab/docassemble-ALWeaver

docassemble/assemblylinewizard/interview_generator.py
If you want to see the deets, you'll have to look at the great commit messages I have on my local repo...
=> Fix `name_full`, implement other conventions

docassemble/assemblylinewizard/interview_generator.py
Does not include:
- plurals (it will come out as `prefixes[0]s` and we'll have to fix that manually`)
- multiple appearances (`__n`)
If those are blockers, they're what I'm working on next. Though we will be fixing a lot of stuff manually anyway.
See all my pretty commits on my local branch until ssh issues get resolved.
=> Implement some names in labeling docs. See notes.

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
https://trello.com/c/PAMFISYo/77-add-progress-100-to-the-download-screen
=> Set download page to 100% progress as per Trello card

docassemble/assemblylinewizard/data/questions/assembly_line.yml
Doing this one small innocuous part at a time.
=> Implement `labels above fields` in wizard.

docassemble/assemblylinewizard/interview_generator.py
=> Fixes no one line in front of `basic_questions_intro_screen`

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
Initial draft of review screens.
Known issues:
The placeholder for built-in variables is not very good.
Specifically: 
1. names are not editable at all, since we display the object and not an editable attribute. 
2. Addresses are editable, but they show only the street address rather than the full address.
3. All of the built-in fields are missing labels.
4. We don't show anything if the value is blank, but we should probably use a placeholder, like "(unanswered)". But think about translation.
One thought is to just write the review screens for all of the built-in variables, maybe using a template, and incorporate that
as part of every auto-generated review screen.
=> Review screen generator

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
Addresses some issues with adding docx variables to fields list, #83
See tests at https://repl.it/@plocket/docxvars#main.py and test with various docx files.
I think this fixes #85 too. That file could be tested here.
=> Troubleshoot some other docx var obstacles. Addresses #83.

docassemble/assemblylinewizard/data/questions/generator-test.yml, docassemble/assemblylinewizard/interview_generator.py
Test: Upload document and continue to the next page without error. Fixes #103.
=> Fix #103, reserved_whole_words not existing

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/generator_constants.py, docassemble/assemblylinewizard/interview_generator.py
Still familiarizing myself with things, but most of these issues were low-hanging fruit, so I went ahead and did them, since I added a bunch of issues today. 
Still need to test that the new address and phone aliases work, and then edit the documentation to update that they exist: https://github.com/SuffolkLITLab/doc-assembly-line/blob/master/labeling-fields.md#field-labels-advanced-lessons
Fixes:
* #102 
* #116 
* #111 
* #109
=> Misc Fixes to the Interview Generator

docassemble/assemblylinewizard/data/questions/assembly_line.yml
=> Close #129, remove none of the above from  screen creation

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
Quick and dirty--we can make more flexible later (e.g., for compatibility w/ other states)
=> Migrate intro screen, includes to new package

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/generator_constants.py, docassemble/assemblylinewizard/interview_generator.py
I think this is at least ready to get some thorough testing. Might be a little rough but it works correctly on the files I tested. We also may have edge cases with DOCX methods that are just not solvable, without some way to annotate them.
=> 163 handle custom people

docassemble/assemblylinewizard/generator_constants.py, docassemble/assemblylinewizard/interview_generator.py
Fixes #188, fixes #239, fixes #240, fixes #237. Test with these docs:
Tested with:
1. [unmap_suffixes.docx](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5990025/unmap_suffixes.docx)
1. [unmap_suffixes.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/5990027/unmap_suffixes.pdf)
=> 188 redo display to settable

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
As opposed to the current error screen.
Fixes #246. 
Looks like:
=> Tell user when they give us a PDF with no fields

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
=> Move interview order higher fix #265 

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
Close #105, add info-only screen.
Test 1 with [info_screen.docx](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6051001/info_screen.docx):
Test 2 with [info_screen.pdf](https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/files/6051030/info_screen.pdf):
=> Close #105, add info-only screen

docassemble/assemblylinewizard/data/questions/assembly_line.yml
=> Add people candidates; fix #257

docassemble/assemblylinewizard/data/questions/assembly_line.yml, docassemble/assemblylinewizard/interview_generator.py
Fixes #256. It does so by just escaping double and single quotes (which allows us to change what quotes we're using without too much issue). `json.dumps` didn't quite work because docassemble seems to have issues with unicode / emoji rendering from `\u1234` strings, giving this error:
```
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 10921, in index
the_phrase = pack_phrase(phrase)
File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/backend.py", line 570, in pack_phrase
phrase = bytearray(phrase, encoding='utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 130-131: surrogates not allowed
```
Have been testing using this file: 
[generic_motion_family_law-bootcamp_copy …
=> Escape user input

docassemble/assemblylinewizard/data/questions/assembly_line.yml
=> Close #128, try different text for adding a continue button

docassemble/assemblylinewizard/interview_generator.py
Fixes #277, was a 6 line change instead of 4 lines, apologies.
=> Stop adding extra newlines after maxlength

docassemble/assemblylinewizard/data/questions/pdf_field_tester.yml
=> PDF pre-flight: always show docassemble internal name if reserved

docassemble/assemblylinewizard/generator_constants.py, docassemble/assemblylinewizard/interview_generator.py
=> Remove redundant constants

docassemble/assemblylinewizard/data/questions/assembly_line.yml
Basically reduce time for install and don't let users try running the interview until it's fully installed.
Fix #331, fix #298
=> Package install improvements

docassemble/assemblylinewizard/interview_generator.py
=> Use the signature_if_final method for ALIndividuals in generated attachment blocks

docassemble/assemblylinewizard/interview_generator.py
Fix #342 
This improves the experience of debugging/testing new output patterns for Weaver developers and has no impact on developers who just use the weaver to make an interview.
=> Fix #342 - defer loading output patterns until rendering the output.

docassemble/assemblylinewizard/test_fill_in_field_attributes.py, docassemble/assemblylinewizard/test_map_names.py
Which just happens when you don't run tests locally. Thanks to #356, we can now!
=> Made the tests actually runnable

.github/workflows/tests.yml, docassemble/assemblylinewizard/interview_generator.py, docassemble/assemblylinewizard/test_map_names.py
Forgot that https://github.com/SuffolkLITLab/docassemble-assemblylinewizard/pull/376 got out of sync with some tests, which actually did catch an error! `.mail_address` was hardcoded in `trigger_gather()`.
Also decided to turn on the unit tests, so tests can run automatically on stuff like this.
=> Fixed broken tests, actually run tests

docassemble/assemblylinewizard/data/questions/pdf_field_tester.yml
Added a customized Continue button and an Exit button/url for issue #367.
=> Merged weaver

docassemble/assemblylinewizard/data/sources/output_patterns.yml
=> Fix incorrectly escaped label for review screen / make changes button

docassemble/ALWeaver/draggable_table.py
=> Stopped keeping extra soup objects around in the global variable space

docassemble/ALWeaver/data/sources/output_patterns.yml, setup.cfg, setup.py
=> Implement T&P UX suggestions - renamed "Make changes" and added more hierarchy to download screen

docassemble/ALWeaver/generator_constants.py, setup.cfg, setup.py
Fix #587
Also caught typo with `interested_partys`
=> Add "adoptees" as a noun

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/visual.yml
=> Hide spurious playground warnings

architecture.md
Fix #221
Open to additions and comments, but I feel OK to add this file as our starting point w/o review.
=> add a short architecture.md file

docassemble/ALWeaver/data/templates/output.mako
Already fixed in a prod interview in,
https://github.com/SuffolkLITLab/docassemble-ALMassachusetts/pull/6, but ran into an issue where a newly generated interview had the same problem.
=> Collect addresses before putting them in a list

docassemble/ALWeaver/interview_generator.py
Even though the variables are coming from a DOCX, we are seeing what would happen if they actually came from a PDF, and if they would change.
=> Revert part of 33308d1e54e3fa0

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/sources/test_1.feature
It should always be plaintiff in that case. Since the screen that asks it also asks other questions, I added a show if.
Also added a weaver test to handle this, and fixed the previous weaver test, which was broken (which wasn't really clear from the logs, as half of the time it's still timing out). But tests pass locally now.
This fixes #699, and also should prevent more issues like https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/596 from arising.
=> Don't show typical_role if form_type = starts_case

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/template_validation.yml, docassemble/ALWeaver/field_grouping.py, docassemble/ALWeaver/interview_generator.py, mypy.ini
Just adding more types, which are usually helpful.
=> More types

docassemble/ALWeaver/data/templates/output_defs.mako
Found with a student, showed up several times in their interview.
Should probably add a test, but diving into Kiln for the Weaver will take a while.
=> Remove extra quote when formatting numbers

docassemble/ALWeaver/custom_values.py, docassemble/ALWeaver/interview_generator.py, mypy.ini
Can start to officially integrate with ALToolbox types, though we don't need any of those changes right now.
=> Type cleanup

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/static/logo.svg, docassemble/ALWeaver/data/static/styles.css
Fix #671
Noticed there were some small misalignments in the SVG as well. I hadn't realized it wasn't a font but was just some primitive paths, but those paths weren't aligned correctly, giving a weird aliasing error.
New: ![image](https://user-images.githubusercontent.com/7645641/204648641-465afcab-bbf1-435b-bf51-ff79e85f147b.png)
Old:
=> Use SVG logo, improve and simplify path

docassemble/ALWeaver/data/questions/assembly_line.yml
=> Fix bug affecting mixed document types in multiweaver

docassemble/ALWeaver/interview_generator.py
Potentially help with closing PDF objects. See https://github.com/jhpyle/docassemble/pull/631 for similar changes, and more details.
=> Close PDF objects when done

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/template_validation.yml
Fix #647 fix #681 address #602 fix #408 fix #741
Per discussion, going to merge but feel free to do a post-merge review/open new issues if anything looks too hackish
=> Opinionated cleanup to prep for LIT Con. 

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/review_screen.yml, docassemble/ALWeaver/interview_generator.py
Some misc. bug fixes mostly in the new code that's been added in the last week + some regressions exposed by adding the review screen.
Fix #768 
Fix #773
=> Regressions

docassemble/ALWeaver/data/questions/template_validation.yml, docassemble/ALWeaver/data/templates/output.mako
=> regression in addendum code in attachment block

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/review_screen.yml, docassemble/ALWeaver/interview_generator.py
Fixes https://github.com/SuffolkLITLab/docassemble-ALWeaver/issues/783; I'll re-open and re-target it to fixing the UX after LITCon.
=> No override

docassemble/ALWeaver/data/questions/assembly_line.yml
Following the conversation in https://github.com/SuffolkLITLab/docassemble-ALWeaver/pull/788#issuecomment-1490926002
=> Move info to help, out of hint

docassemble/ALWeaver/data/questions/assembly_line.yml
Should fix it, but I'm not sure how to test the I'm feeling lucky, since it can only be started from the form-explorer. @nonprofittechy  how have you been testing it?
=> Set 'choices' for radio buttons when feeling lucky

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/sources/test_1.feature, docassemble/ALWeaver/generator_constants.py, docassemble/ALWeaver/test_map_names.py
Got lost in the rush last week
=> Add case numbers as a thing the weaver can recognize

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/sources/test_1.feature, docassemble/ALWeaver/interview_generator.py, docassemble/ALWeaver/requirements.txt, docassemble/ALWeaver/validate_template_files.py
Fix #571 
This works on the apps-dev server, but I'm noting that tests are not passing. I'll try updating version of FormFyxer to see if that resolves it.
=> Inline feeling lucky

docassemble/ALWeaver/data/questions/template_validation.yml
Going to merge, hotfix to broken feature
=> fix broken field renaming

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/review_screen.yml
=> Add basic left navigation

README.md, docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/review_screen.yml, docassemble/ALWeaver/data/sources/test_1.feature, docassemble/ALWeaver/interview_generator.py, setup.py
Handle installation + fallbacks for en_core_web_lg
Fix #859 
Fix #858 
Fix #857 
Fix #856
=> Make it easier to use auto drafting mode without manual installation of en_core_web_lg

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/data/questions/review_screen.yml, docassemble/ALWeaver/data/templates/output.mako, docassemble/ALWeaver/interview_generator.py
Fix #874 
Fix #870 - Allow editing more things from auto drafting mode, esp. categories
Fix #823  - don't add code/skip fields to the review screen
=> Bug fixes related to review screen generating and editing

.github/workflows/black_linter.yml
The action-black action at that version is broken
=> Use ALActions/black-formatting

docassemble/ALWeaver/data/questions/review_screen.yml
=> Use accordions on review page

docassemble/ALWeaver/data/questions/assembly_line.yml
=> Make filename lowercase by default even if input or title are uppercase

docassemble/ALWeaver/data/questions/review_screen.yml, docassemble/ALWeaver/data/static/draggable_table.css, docassemble/ALWeaver/data/static/draggable_table.js, docassemble/ALWeaver/data/static/styles.css, docassemble/ALWeaver/draggable_table.py
=> Improve the look and feel of the preview and screen reordering with minor CSS changes

docassemble/ALWeaver/data/questions/assembly_line.yml, docassemble/ALWeaver/interview_generator.py, setup.py
=> don't try to install spaCy at runtime or require it
